from enum import Enum


class SyncEventType(str, Enum):
    DOOR_SET_STATUS = "DOOR_SET_STATUS"
    ADDON_FACT_CREATE = "ADDON_FACT_CREATE"


class SyncChangeType(str, Enum):
    DOOR = "DOOR"
    ADDON_FACT = "ADDON_FACT"
    PROJECT_ADDON_PLAN = "PROJECT_ADDON_PLAN"
    PROJECT_ASSIGNMENTS = "PROJECT_ASSIGNMENTS"
    PROJECT_BASE = "PROJECT_BASE"
    CATALOG_ADDON_TYPES = "CATALOG_ADDON_TYPES"
